### ISSUE TITLE
limesurvey-3.x version bump

### ISSUE THREAD

**Issue by stefangweichinger** [crramirez/limesurvey#22]
It would be great to have 3.x from scratch (instead ov having to upgrade the fresh container every time).

**Comment by crramirez** [comment]
Hello @stefangweichinger 

I am working in a new container for limesurvey 3.x. The problem is that I am trying to use official base containers for php and mysql, and the thing is getting complicated to maintain the same structure as the actual version.

One question. As I understand you were able to use the container and upgrade it to limesurver 3? I tried this months ago and I couldn't. This definitely will speed up the process to have a container with limesurve 3.

Regards

**Comment by stefangweichinger** [comment]
I found acspri/limesurvey in the meantime ... but having issues with that one as well.

I was able to use ComfortUpdate within a container based on your image (do I use the right terms?), it worked and I got 3.1.14 (as far as I remember right now). But the part with the design templates didn't work and also file uploads failed (I logged in and checked/enhanced permissions ... without success).

Currently I have various instances running, and losing track slowly ;-) If I can help in a way, let me know.

**Comment by crramirez** [comment]
Ok excellent information. I will try again to upgrade the limesurvey
version in the container. I think that fixing the upload and design
templates is something doable in a reasonable time. I will inform everyone
in this issue the progress

**Comment by stefangweichinger** [comment]
It's unclear to me if uploading files and/or design template part fails because of the upgrade or because of the new release. Maybe conflicting directories/files stay installed where they shouldn't, etc etc

As I am rather new to docker I also wonder if the reverse proxy (nginx-proxy, or traefik) could play a role here ... although I have a non-docker VM with same issues as well. And I can test locally without proxies, if needed. Looking forward to any news here, thanks.

**Comment by crramirez** [comment]
Hello,

Looks like it worked! Please check the release:

https://github.com/crramirez/limesurvey/releases/tag/3.14.3 

Or

docker pull crramirez/limesurvey:3.14.3

In fact upload is not working yet, probably I need to adjust the htaccess file. 

PLEASE do not upgrade a production environment without backing up and this is a pre release, don't use it in a production environment.

Please test and tell me if you find something

Regards,
Carlos

**Comment by stefangweichinger** [comment]
Tested a container with crramirez/limesurvey:3.14.3, installs and starts, installer OK, login OK.
Menu "Themes" opens OK (had that one crashing as well with another updated instance), but upload is not working yet, as you mentioned.

I tried to chmod the ./tmp dir and editing .htaccess, without success so far. It would be great to solve this soon, as my customer already waits to create/edit his new templates in a test-container ;-)

thanks, regards, Stefan

**Comment by stefangweichinger** [comment]
ping @crramirez : any news around that permission issue?

**Comment by crramirez** [comment]
Hello Stefan,

No, I am dealing with it, it should work due to apache is correctly
configured for .htaccess. I will try this week other options to leave it
working.

**Comment by stefangweichinger** [comment]
ok, thanks. Are you sure that it isn't an upstream bug in limesurvey itself?
At upgrade time it runs various tests and all is OK/green ...

**Comment by stefangweichinger** [comment]
btw: I was informed that the next upgrade is coming:

> LimeSurvey LTS version 3.0 will be supplied with security updates until the end of 2019. In the meantime, preparations are made for the release of LimeSurvey 4.0 which is scheduled roughly for the end of 2018 to the start of 2019.

**Comment by crramirez** [comment]
Hello,

I tried in many ways without success to make the Upload functionality work. So, I will return to the approach to container re-engineering that is something that eventually must be done.

Regards

**Comment by crramirez** [comment]
Well, after doing a pre re-engineering I found the same error. So, I returned to the original container and digged a little more in google and found the solution. I published a new release **3.14.3-1** please test it. If everything goes ok I will publish as a complete release and update the docker hub page. 

Test with 

> docker pull crramirez/limesurvey:3.14.3-1

Also I will soon publish the new version as an alternate branch with php7 and new os image all based in official images. This is based on the work of @adamzammit

**Comment by stefangweichinger** [comment]
great to hear, I will re-pull and test asap (maybe later this week as other issues have higher priority for my customer right now). thanks!

**Comment by crramirez** [comment]
Try with docker-compose down -v first it will destroy all data and volumes

**Comment by stefangweichinger** [comment]
even after destroying and recreating same error

**Comment by crramirez** [comment]
Sorry @stefangweichinger I didn't make a good test before the release. Now it is fixed. Please download the 3.14.3-2 release

**Comment by stefangweichinger** [comment]
@crramirez : thanks for the new image, I get through the installer without error, but uploading an image (in Theme-Options) still fails with 

> An error occurred uploading your file. This may be caused by incorrect permissions for the application /tmp folder.

Yes, I destroyed the volumes before recreating the new container with the -2 release.

**Comment by crramirez** [comment]
Check this: https://www.limesurvey.org/es/foro/can-i-do-this-with-limesurvey/116415-cannot-upload-images-to-template

**Comment by stefangweichinger** [comment]
sounds promising, will test, thanks

**Comment by stefangweichinger** [comment]
Are the latest images online? I get problems at pulling:

```
# docker pull crramirez/limesurvey:3.14.3-1
Error response from daemon: manifest for crramirez/limesurvey:3.14.3-1 not found
# docker pull crramirez/limesurvey:3.14.3-2
Error response from daemon: manifest for crramirez/limesurvey:3.14.3-2 not found
```

pls advise. (gonna deploy a test-instance to users at customer asap)

**Comment by crramirez** [comment]
docker pull crramirez/limesurvey:3.15.0_181008 or docker pull
crramirez/limesurvey:3

**Comment by stefangweichinger** [comment]
@crramirez thanks, works! I am gonna write an ansible-playbook for deploying the instance, maybe you are interested in adding that later?

**Comment by crramirez** [comment]
Excellent I will then begin the process of changing the default image from
2 to 3.

Yes, We can add the ansible-playbook to the project

**Comment by stefangweichinger** [comment]
@crramirez I agree on that ... release 4.x is announced for early 2019 ;-)

**Comment by stefangweichinger** [comment]
@crramirez I clicked through the installer and after that login failed. In the console I see a 100% full root-filesystem ... any idea on that? Maybe some cleanup step missing somewhere?

**Comment by crramirez** [comment]
Check the space available in your host.

**Comment by crramirez** [comment]
Hello,

crramirez/limesurvey:latest now points to verision 3.x. If you want to use version 2 use:

docker pull crramirez/limesurvey:2

This finish this issue

Regards
